version: '3.9'
services:
  frontend:
    container_name: todo_frontend
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      # lsof: list open files (lista os processos em uma porta especifica -i)
      # -t: lista os processos em background (para nao travar o container)
      timeout: 10s
      retries: 4
  backend:
    container_name: todo_backend
    build: ./backend
    ports:
      - 3001:3001
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=3001
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_HOST=db
      - DB_NAME=TODO_LIST
      - DB_PORT=3306
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 4
  db:
    image: mysql:8.0.21
    container_name: todo_db
    ports:
      - 3002:3306
    environment:
      MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 4
    cap_add:
      - SYS_NICE